name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      run: echo "RUBY_VERSION=$(cat ruby-version)" >> $GITHUB_ENV
    - name: Run tests
      run: bundle exec rspec test
